# Generated by Django 3.2.20 on 2023-08-31 22:16

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('satmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='map',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='map',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
        migrations.AlterField(
            model_name='map',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17),
        ),
    ]
