# Generated by Django 3.2.20 on 2023-08-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
