# Generated by Django 3.2.20 on 2023-08-15 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satmap', '0002_auto_20230810_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='opacity',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
