# Generated by Django 3.2.20 on 2023-08-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satmap', '0004_alter_layer_opacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='map',
            name='layer',
        ),
        migrations.AddField(
            model_name='map',
            name='layer',
            field=models.ManyToManyField(blank=True, to='satmap.Layer'),
        ),
    ]
