# Generated by Django 3.2.20 on 2023-08-16 20:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satmap', '0005_auto_20230815_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='palette',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=['blue', 'purple', 'cyan', 'green', 'yellow', 'red'], size=None),
        ),
    ]
