# Generated by Django 3.2.20 on 2023-08-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satmap', '0006_layer_palette'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
