# Generated by Django 3.2.20 on 2023-08-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satmap', '0008_auto_20230817_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='palette',
            field=models.TextField(default="'blue', 'purple', 'cyan', 'green', 'yellow', 'red'"),
        ),
    ]
