# Generated by Django 3.2.20 on 2023-08-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satmap', '0010_layer_is_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='units',
            field=models.CharField(default='units', max_length=255),
        ),
    ]
