# Generated by Django 3.2.20 on 2023-08-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satmap', '0011_layer_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='units',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
