# Generated by Django 3.2.20 on 2023-08-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satmap', '0012_alter_layer_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
