# Generated by Django 3.2.20 on 2023-08-30 22:03

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('satmap', '0013_layer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
